// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCqS5Uuf9ZqgfqbdWlJKGTcccBPI5wB8',
    appId: '1:35791080832:ios:7d79aedf6902d80470c565',
    messagingSenderId: '35791080832',
    projectId: 'fir-3d80e',
    databaseURL:
        'https://fir-3d80e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-3d80e.appspot.com',
    iosBundleId: 'com.example.youTubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHu-xkt7HbVU70nFokw5PhNCr-FSBbso',
    appId: '1:35791080832:web:e95c3a2b11c72e2870c565',
    messagingSenderId: '35791080832',
    projectId: 'fir-3d80e',
    authDomain: 'fir-3d80e.firebaseapp.com',
    databaseURL:
        'https://fir-3d80e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-3d80e.appspot.com',
    measurementId: 'G-TY8NFLQS77',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHu-xkt7HbVU70nFokw5PhNCr-FSBbso',
    appId: '1:35791080832:web:e95c3a2b11c72e2870c565',
    messagingSenderId: '35791080832',
    projectId: 'fir-3d80e',
    authDomain: 'fir-3d80e.firebaseapp.com',
    databaseURL:
        'https://fir-3d80e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-3d80e.appspot.com',
    measurementId: 'G-TY8NFLQS77',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCqS5Uuf9ZqgfqbdWlJKGTcccBPI5wB8',
    appId: '1:35791080832:ios:7d79aedf6902d80470c565',
    messagingSenderId: '35791080832',
    projectId: 'fir-3d80e',
    databaseURL:
        'https://fir-3d80e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-3d80e.appspot.com',
    iosBundleId: 'com.example.youTubeClone',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbWisIz7ZJ0LPguh0d6xUCYML_UY3UcE',
    appId: '1:35791080832:android:9375058a37f4d58670c565',
    messagingSenderId: '35791080832',
    projectId: 'fir-3d80e',
    databaseURL:
        'https://fir-3d80e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-3d80e.appspot.com',
  );
}
